name: controle_gasto_pessoal
description: Aplicativo de controle financeiro pessoal
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true