name: controle_gasto_pessoal
description: "Controle de Gasto Pessoal."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  fl_chart: ^0.63.0
  intl: ^0.18.1
  pdf: ^3.8.4
  printing: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
